### ISSUE TITLE
Compiling the DWSWebServer.dpr fails

### ISSUE THREAD

**Issue by adem0x** [EricGrange/DWScript#1]
Using the latest sources and compiling the DWSWebServer.dpr has a lot of problems.

Apart from the various small issues that I could solve, it seems to require units in Libraries\JSCodeGen from DWS v2.2 which are no more available in DWS v2.3.

But, even if I supply the units from JSCodeGen, the compilation does not succeed --classes have been renamed, methods and parameters are different etc.

IOW, too numerous to list here..

Could you please update the sources so that all units that are needed for DWSWebServer.dpr are in this repository and that they compile.

Thank you.

**Comment by EricGrange** [comment]
Pushed a few ifdef changes, is it okay now?

**Comment by adem0x** [comment]
Thank you; with your changes I got it to compile and run (from BitBucket repo).

One minute thing that needs to be corrected for successful compilation:

in dwsWindowsService.pas, the var list for TdwsWindowsService.LaunchedBySCM needs to be like this:

  scHandle: THandle;
  svInfo: Integer;
  servStat: WinSvc.TServiceStatus; {since mormot also has this defined, this must be explicit.}

And, once the server is running:

www\res\DWS_server.jpg is missing from the repo, could you please add it there.

But, that's not the end of it: When I add it there manually, it is not displayed in the browser http://localhost:888/

One more thing, there are references to some files (namely, '.startup.pas', '.shutdown.pas') in cDefaultCPUOptions (in DSimpleDWScript.pas), but they don't exist under the 'www' folder.

While they don't seem to be essential for the running of the server, it would be helpful if they were there so that I/we could use them as templates.
