### ISSUE TITLE
dwsUTF8.pas needs SynCommons from the deprecated mORMot 1

### ISSUE THREAD

**Issue by jonjbar** [EricGrange/DWScript#12]
The dwsUTF8.pas unit needs the SynCommons from the deprecated mORMot 1: https://github.com/synopse/mORMot

The problem is that this file is not only needed for demos, but for the compiler too. This creates a dependency to a huge and unmaintained project, which might conflict with newer versions.

**Comment by EricGrange** [comment]
Yes, the functions have been segregated to a special unit so alternative implementations are easy to provide/include, but I have not yet had time to review them. The RTL's implementation should be straightforward to redirect too, but it's a bit sluggish, having a built-in implementation (without 3rd party dependency) would be preferable.

**Comment by EricGrange** [comment]
UTF-8 conversions functions now have a new implementation (should be as fast or faster than mORMot1)
