### ISSUE TITLE
DWScript on android

### ISSUE THREAD

**Issue by achinastone** [EricGrange/DWScript#13]
I try to use DWScript on android. And it runs. 
But timer may occasionally be a null pointer. See the follow code

I have made the following modifications, I am not sure if they are feasible

` procedure TdwsXTimerQueueWorker.Execute;
  var   
     I: Integer;
     TotalTimeouts: Int64;
     Timer: TdwsXTimer;
     Error: Integer;
  begin   
     while not Terminated do
     begin  
       NumberOfEvents := epoll_wait(FOwner.Handle, @FEvents, MAX_EVENTS, 100);
       if NumberOfEvents = 0 then Continue else
       if NumberOfEvents = -1 then 
       begin  
           Error := errno;
           if Error = EINTR then Continue else Break;
        end;
        for I := 0 to NumberOfEvents - 1 do
        begin
          try  
             Timer := FEvents[I].data.ptr;  // <==  Timer maybe nil 
             if not Assigned(Timer) then
                continue;

              if not Timer.FClose then
              begin
                 if (FEvents[I].events AND EPOLLIN) = EPOLLIN then
                 begin
                    if __read(Timer.Handle, @TotalTimeouts, SizeOf(TotalTimeouts)) >= 0 then
                    begin
                       if Assigned(Timer.FOnTimer) then Timer.FOnTimer(@Timer,true);
                    end else Timer.FClose := True;
                 end;
              end;
          finally
             if Assigned(Timer) then // <==  Timer maybe nil
             begin
               if Timer.FClose then
               begin
                  epoll_ctl(_TimerQueuePool.Handle, EPOLL_CTL_DEL, Timer.Handle, @Event); { -1 on error }
                 __close(Timer.Handle);
                 Timer.FClosed.SetEvent;
               end;
             end;
          end;
        end;
     end;
  end;`

**Comment by EricGrange** [comment]
Thanks, applied your change (this unit was contributed, I have never used it so far)

**Comment by achinastone** [comment]
The line ` if not Timer.FClose then` lack of pointer check.
Should be `if Assigned(Timer) and (not Timer.FClose) then`
