### ISSUE TITLE
Evaluating an expression in the context of a script method

### ISSUE THREAD

**Issue by andersmelander** [EricGrange/DWScript#4]
I am trying to evaluate an expression Delphi-side, using `TdwsEvaluateExpr.Evaluate`. The expression must be compiled and executed in the context of a specific script side object/method.

For example, let’s say I have the following script class `TScriptClass` declared in a `TdwsUnit` and the corresponding class implemented in Delphi as `TDelphiClass`:

```Delphi
type
  TScriptClass = class
    ...
  public
    // Simple getter/setters. Just forwards to the Delphi side property getter/setters
    property Count: Float read GetCount write SetCount;
    property Price: Float read GetPrice write SetPrice;
    property Expression: string read GetExpression write SetExpression;

    property Value: Float read GetValue;
  end;
```

The idea is that the **Expression** specifies how the **Value** is calculated. An example expression could be: `Count * Price`

The Delphi-side implementation of the `GetValue` script method looks like this:

```Delphi
procedure TDataModuleScript.dwsUnitTestClassesTScriptClassMethodsGetValueEval(Info: TProgramInfo;
  ExtObject: TObject);
begin
  var DelphiObject := TDelphiClass(ExtObject);
  if (DelphiObject.Expression = '') then
    exit;

  var Expr := TdwsEvaluateExpr.Evaluate(Info.Execution, DelphiObject.Expression);

  if (Expr.Expression.Typ = nil) then
    exit;

  Info.ResultAsFloat := Expr.Expression.Eval(Info.Execution);
end;
```

While this works fine for evaluating expressions in the global context, it fails to resolve references to symbols in the local context. That means that in the `Count * Price` expression example the class symbols **Count** and **Price** are unknown.

Is this a bug, am I using the wrong execution context, or is what I’m trying to do simply not possible?

**Comment by andersmelander** [comment]
> If you want to evaluate an expression in the context of a method, you should use TdwsEvaluateExpr when that context is active

This is precisely what I'm doing - or at least that's what I think I'm doing :-) :

```Delphi
procedure TDataModuleScript.dwsUnitTestClassesTScriptClassMethodsGetValueEval(Info: TProgramInfo;
  ExtObject: TObject);
begin
  var DelphiObject := TDelphiClass(ExtObject);
  if (DelphiObject.Expression = '') then
    exit;

  var Expr := TdwsEvaluateExpr.Evaluate(Info.Execution, DelphiObject.Expression);

  if (Expr.Expression.Typ = nil) then
    exit;

  Info.ResultAsFloat := Expr.Expression.Eval(Info.Execution);
end;
```

`DelphiObject.Expression` is a string containing the expression, supplied by the Delphi-side object.

My assumption is that `Info.Execution` provides the context for the evaluation of the expression to `TdwsEvaluateExpr`.

The whole thing is being called from a script-side method (in the above example, a property getter) so the context should be there - somewhere.

I can make a minimal example if you like, but it's really not much more that the code above.

**Comment by EricGrange** [comment]
Yes, please, if you have a minimal case (I would then add it to the test cases if appropriate)

**Comment by andersmelander** [comment]
Here's a minimal'ish demo.
![billede](https://github.com/EricGrange/DWScript/assets/18141921/75c65a5b-687c-4f23-b574-bf5eaa8a340b)

[ExpressionEvaluation.zip](https://github.com/EricGrange/DWScript/files/14452174/ExpressionEvaluation.zip)

**Comment by andersmelander** [comment]
There's a minor bug in the demo; Delete the line `MemoOutput.Lines.Text := dwsExecution.Msgs.AsInfo` - It overwrites the output from the `WriteLn`. Doesn't really affect the core problem though.

**Comment by EricGrange** [comment]
Oh, ok, I did not understood what you were trying. This is failing because the evaluation is meant for debug, and there is no script-side method in the script, so it has no "scriptPos" (source file / line / column) to figure out the context.

If you really want to use a TdwsEvaluateExpr, it needs a method on the script-side, one way to do it would be rewrite your script like this:
 
 ```
type
   TSub = class (TScriptClass)
       function GetValue : Float;
       begin
          Result := Value;
       end;
   end;

var ScriptObject := TSub.Create;

ScriptObject.Count := 42;
ScriptObject.Price := 13;
ScriptObject.Expression := '(Count * Price) * 1.25';

WriteLn(ScriptObject.GetValue);
```

However this would be very inefficient, because the TdwsEvaluateExpr would trigger a whole compilation of the expression at each evaluation plus a nested call.

A more efficient approach may be be compile your expression directly in the script, by injecting in GetValue, something like
 
```
type
   TSub = class (TScriptClass)
       function GetValue : Float; override;
       begin
          Result := (Count * Price) * 1.25;
       end;
   end;
```
   
or even if you want/can avoid a virtual method

```
type
   TSub = class (TScriptClass)
      property Value : Float read ((Count * Price) * 1.25);
   end;
```
   
Unless your script is very large, recompiling the whole script should be quickly amortized vs using EvaluateExpr, plus you could then benefit from JIT.

Another thing to consider for performance (that may not apply to your case) would be doing away with the individual calls to the Delphi-side class for each property, and instead declare the properties in the script class, and assign them all at once when creating the script class. This will avoid jumps between script and Delphi-sides (which can be quite costly) and open up more JIT optimizations.

**Comment by andersmelander** [comment]
> This is failing because the evaluation is meant for debug, and there is no script-side method in the script, so it has no "scriptPos" (source file / line / column) to figure out the context.

Yes, I actually already figured out, from tracing through the code, that the lack of a current scriptPos was what caused the incorrect evaluation context. I just hoped that there was some way around that that I had missed.

I can't work around this with script injection or the like because there actually is no script. All the objects, and there will be tens of thousands of then, are "internal" (`isInternal=True`) and organized in a tree-like structure. The expression evaluation is mostly triggered from Delphi-side when the object properties are read. Expressions can reference properties of other objects which in turn might trigger evaluation of other expressions.

The whole system will also be using "regular" scripts that needs access to the objects and their properties (including the evaluated ones) but that is separate from the expression evaluation.

We already have a non-DWScript expression evaluation engine in use that could be used for this but it would be much better to use DWScript both because it would provide a more consistent experience for the user and we would avoid having to replicate and duplicate functionality between the two systems.

The fact that there isn't a script to inject into might actually be an advantage because it means that we can simply synthesize a complete standalone script based on the expression, similar to what you suggested, and then execute that when the expression needs to be evaluated. This would also have the benefit of the expression tree being cacheable which would have a very positive impact on performance.

I'll give it a go and let you know how it turns out.

**Comment by EricGrange** [comment]
If your whole external class hierarchy is static (or static enough, ie. only updated by BPLs/DLLs), it should be possible to build a massive script with all the methods, but only once. Then you could either inject there, or if going the TdwsEvaluateExpr way, cache them for the nested calls.
EvaluateExprs are valid for the lifetime of a given compilation and execution (they were intended for debug evals, watches and conditional breakpoints), so if you don't have multiple script executions, you can reuse them, which would at avoid compiler roundtrips per evaluation.
