### ISSUE TITLE
Can dwscript runs on Android and iOS platforms

### ISSUE THREAD

**Issue by achinastone** [EricGrange/DWScript#5]

**Comment by EricGrange** [comment]
I have never tested, nor I have the Android / iOS Delphi compilers installed.
If the Android/iOS code still uses the ARC compiler, I suspect it won't work.

**Comment by achinastone** [comment]
Thanks very much，do you have the plan?

**Comment by achinastone** [comment]
When I install dwscript to the DelphiIDE.
I can not put the dwscript component to the FMX forms.

**Comment by EricGrange** [comment]
In addition to creating it manually, if data modules are still supported in Android/FMX, you should be able to put it there.

**Comment by achinastone** [comment]
Thanks, I will have a try.

**Comment by achinastone** [comment]
dwsXPlatform.pas is not compiled under android. 

  [DCC Error] dwsXPlatform.pas(64): E2029 Identifier expected but ',' found
  [DCC Error] dwsXPlatform.pas(101): E2003 Undeclared identifier: 'TRTLCRiticalSection'
  [DCC Error] dwsXPlatform.pas(102): E2007 Constant or type identifier expected
  [DCC Error] dwsXPlatform.pas(498): E2003 Undeclared identifier: 'GetFileSizeEx'
  [DCC Error] dwsXPlatform.pas(501): E2003 Undeclared identifier: 'CreateFileMapping'
  [DCC Error] dwsXPlatform.pas(501): E2003 Undeclared identifier: 'PAGE_READONLY'
  [DCC Error] dwsXPlatform.pas(505): E2003 Undeclared identifier: 'MapViewOfFile'
  [DCC Error] dwsXPlatform.pas(505): E2003 Undeclared identifier: 'FILE_MAP_READ'
  [DCC Error] dwsXPlatform.pas(509): E2003 Undeclared identifier: 'CloseHandle'
  [DCC Error] dwsXPlatform.pas(526): E2003 Undeclared identifier: 'UnmapViewOfFile'
  [DCC Error] dwsXPlatform.pas(530): E2003 Undeclared identifier: 'CloseHandle'
  [DCC Error] dwsXPlatform.pas(641): E2003 Undeclared identifier: 'GetSystemTimeAsFileTime'
  [DCC Error] dwsXPlatform.pas(658): E2003 Undeclared identifier: 'GetSystemTimeAsFileTime'
  [DCC Error] dwsXPlatform.pas(668): E2003 Undeclared identifier: 'WCHAR'
  [DCC Error] dwsXPlatform.pas(669): E2003 Undeclared identifier: 'TSystemTime'
  [DCC Error] dwsXPlatform.pas(671): E2007 Constant or type identifier expected
  [DCC Error] dwsXPlatform.pas(672): E2007 Constant or type identifier expected
  [DCC Error] dwsXPlatform.pas(674): E2007 Constant or type identifier expected
  [DCC Error] dwsXPlatform.pas(680): E2070 Unknown directive: 'delayed'
  [DCC Error] dwsXPlatform.pas(681): E2003 Undeclared identifier: 'USHORT'
  [DCC Error] dwsXPlatform.pas(682): E2003 Undeclared identifier: 'TTimeZoneInformation'
  [DCC Error] dwsXPlatform.pas(682): E2003 Undeclared identifier: 'BOOL'
  [DCC Error] dwsXPlatform.pas(682): E2070 Unknown directive: 'delayed'
  [DCC Error] dwsXPlatform.pas(683): E2003 Undeclared identifier: 'PTimeZoneInformation'
  [DCC Error] dwsXPlatform.pas(684): E2005 'TSystemTime' is not a type identifier
  [DCC Error] dwsXPlatform.pas(684): E2005 'BOOL' is not a type identifier
  [DCC Error] dwsXPlatform.pas(684): E2070 Unknown directive: 'delayed'
  [DCC Error] dwsXPlatform.pas(874): E2003 Undeclared identifier: 'ucol_strcoll'
  [DCC Error] dwsXPlatform.pas(874): E2003 Undeclared identifier: 'GetCollator'
  [DCC Error] dwsXPlatform.pas(887): E2003 Undeclared identifier: 'NORM_IGNORECASE'
  [DCC Error] dwsXPlatform.pas(888): E2003 Undeclared identifier: 'CompareStringEx'
  [DCC Error] dwsXPlatform.pas(891): E2003 Undeclared identifier: 'CSTR_EQUAL'
  [DCC Error] dwsXPlatform.pas(907): E2003 Undeclared identifier: 'ucol_strcoll'
  [DCC Error] dwsXPlatform.pas(907): E2003 Undeclared identifier: 'GetCollator'
  [DCC Error] dwsXPlatform.pas(1377): E2003 Undeclared identifier: 'SysUtils'
  [DCC Warning] dwsXPlatform.pas(1379): W1000 Symbol 'faVolumeID' is deprecated
  [DCC Error] dwsXPlatform.pas(1398): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(1398): E2014 Statement expected, but expression of type 'Boolean' found
  [DCC Error] dwsXPlatform.pas(1401): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(1484): E2003 Undeclared identifier: 'SysUtils'
  [DCC Error] dwsXPlatform.pas(1490): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(1490): E2014 Statement expected, but expression of type 'Boolean' found
  [DCC Error] dwsXPlatform.pas(1493): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(2153): E2003 Undeclared identifier: 'SysUtils'
  [DCC Error] dwsXPlatform.pas(2181): E2003 Undeclared identifier: 'SysUtils'
  [DCC Error] dwsXPlatform.pas(2194): E2003 Undeclared identifier: 'SysUtils'
  [DCC Error] dwsXPlatform.pas(2216): E2003 Undeclared identifier: 'SysUtils'
  [DCC Error] dwsXPlatform.pas(2216): E2010 Incompatible types: 'Pointer' and 'procedure, untyped pointer or untyped parameter'
  [DCC Error] dwsXPlatform.pas(2220): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(2244): E2003 Undeclared identifier: 'SysUtils'
  [DCC Error] dwsXPlatform.pas(2244): E2010 Incompatible types: 'Pointer' and 'procedure, untyped pointer or untyped parameter'
  [DCC Error] dwsXPlatform.pas(2248): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(2252): E2021 Class type required
  [DCC Error] dwsXPlatform.pas(2275): E2003 Undeclared identifier: 'Winapi'
  [DCC Error] dwsXPlatform.pas(2275): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(2340): E2003 Undeclared identifier: 'SysUtils'
  [DCC Error] dwsXPlatform.pas(2364): E2003 Undeclared identifier: 'AsLocalDateTime'
  [DCC Error] dwsXPlatform.pas(2370): E2023 Function needs result type
  [DCC Error] dwsXPlatform.pas(2370): E2029 Declaration expected but '(' found
  [DCC Error] dwsXPlatform.pas(2384): E2066 Missing operator or semicolon
  [DCC Error] dwsXPlatform.pas(2384): E2003 Undeclared identifier: 'hFile'
  [DCC Error] dwsXPlatform.pas(2390): E2023 Function needs result type
  [DCC Error] dwsXPlatform.pas(2390): E2029 Declaration expected but '(' found
  [DCC Error] dwsXPlatform.pas(2390): E2029 '=' expected but ';' found
  [DCC Error] dwsXPlatform.pas(2390): E2029 ';' expected but ')' found
  [DCC Error] dwsXPlatform.pas(2390): E2029 '=' expected but ';' found
  [DCC Error] dwsXPlatform.pas(2405): E2026 Constant expression expected
  [DCC Error] dwsXPlatform.pas(2406): E2029 '..' expected but ';' found
  [DCC Error] dwsXPlatform.pas(2409): E2029 'THEN' expected but identifier 'FindFirst' found
  [DCC Error] dwsXPlatform.pas(2440): E2023 Function needs result type
  [DCC Error] dwsXPlatform.pas(2440): E2029 Declaration expected but '(' found
  [DCC Error] dwsXPlatform.pas(2440): E2029 '=' expected but ')' found
  [DCC Error] dwsXPlatform.pas(2440): E2029 '(' expected but ';' found
  [DCC Error] dwsXPlatform.pas(2441): E2066 Missing operator or semicolon

**Comment by achinastone** [comment]
Symbols that depend on the Windows platform：
TRTLCRiticalSection
TFileTime FILETIME
AcquireSRWLockExclusive
GetFileSizeEx
CreateFileMapping UnmapViewOfFile MapViewOfFile CloseHandle 
GetSystemTimeAsFileTime
GetDynamicTimeZoneInformation

**Comment by EricGrange** [comment]
There are currently no ifdef for Android in dwsXPlatform, , and no mapping or dependencies to units that support Android, some might be similar to those for the UNIX conditional ifdef, you could try forcing it, but beyond that this will be something to be looked at by someone with access to the Delphi Android compiler :/
